### ISSUE TITLE
предпатч дренор квесты

### ISSUE THREAD

**Issue by Cyberdyne-Systems101** [welder1976/bugreport-legacy-Dreanor#1]
Волджину не сдается последний квест для получения пета  "железной звездочки" 
![WoWScrnShot_081220_132649](https://user-images.githubusercontent.com/69580362/90005352-c1597e80-dc9f-11ea-9018-9c9e8cbb726a.jpg)

критичность: низкая

**Comment by Cyberdyne-Systems101** [comment]
> Волджину не сдается последний квест для получения пета "железной звездочки"
> ![WoWScrnShot_081220_132649](https://user-images.githubusercontent.com/69580362/90005352-c1597e80-dc9f-11ea-9018-9c9e8cbb726a.jpg)

критичность: низкая

**Comment by welder1976** [comment]
исправлено
