### ISSUE TITLE
Раздавленный путешественник(npc=83741)

### ISSUE THREAD

**Issue by SimeonGavrilov** [welder1976/bugreport-legacy-Dreanor#16]
1)Раздавленный путешественник
2)https://ru.wowhead.com/npc=83741
3)Отсутствует в указанной точке.
4) Должен находится в указанной точке + иметь при себе (https://ru.wowhead.com/object=233457), в котором содержится (https://ru.wowhead.com/item=116640)
5) Критичность низкая (1)

**Comment by welder1976** [comment]
исправлено
