### ISSUE TITLE
Яйцо золотой калири(object=233134)

### ISSUE THREAD

**Issue by SimeonGavrilov** [welder1976/bugreport-legacy-Dreanor#21]
1)Яйцо золотой калири
2)https://ru.wowhead.com/object=233134
3)Отсутствует на нужных координатах.
4)Должен присутствовать + содержать в себе (https://ru.wowhead.com/item=118266) как 100% лут.
5)Критичность низкая (1)

**Comment by welder1976** [comment]
исправлено
