### ISSUE TITLE
Потерянная подвеска(object=233651)

### ISSUE THREAD

**Issue by SimeonGavrilov** [welder1976/bugreport-legacy-Dreanor#22]
1)Потерянная подвеска
2)https://ru.wowhead.com/object=233651
3)Отсутствует на нужных координатах.
4)Должна находиться на положенном месте + иметь в себе (https://ru.wowhead.com/item=116687) как 100% лут.
5)Критичность низкая (1)

**Comment by welder1976** [comment]
исправлено
