### ISSUE TITLE
Тринадцатый топор Поккара(object=233561)

### ISSUE THREAD

**Issue by SimeonGavrilov** [welder1976/bugreport-legacy-Dreanor#23]
1)Тринадцатый топор Поккара
2)https://ru.wowhead.com/object=233561
3)Отсутствует на нужных координатах.
4)Должен находиться на положенном месте + иметь в себе (https://ru.wowhead.com/item=116688) как 100% лут.
5)Критичность низкая (1)

**Comment by welder1976** [comment]
исправлено
