### ISSUE TITLE
Осколок Ошу'гуна(object=233560)

### ISSUE THREAD

**Issue by SimeonGavrilov** [welder1976/bugreport-legacy-Dreanor#25]
1)Осколок Ошу'гуна
2)https://ru.wowhead.com/object=233560
3)Отсутствует на нужных координатах.
4)Должен находиться на положенном месте + иметь в себе (https://ru.wowhead.com/item=117981) как 100% лут.
5)Критичность низкая (1)

**Comment by welder1976** [comment]
исправлено
