### ISSUE TITLE
Смертоцикл вождя(item=116788)

### ISSUE THREAD

**Issue by SimeonGavrilov** [welder1976/bugreport-legacy-Dreanor#35]
1)Смертоцикл вождя
2)https://ru.wowhead.com/item=116788
3) Продаётся у НПС (https://ru.wowhead.com/npc=73151) за бесплатно.
4) Как минимум должен продаваться за (https://ru.wowhead.com/item=103533). А, возможно, его вообще там не должно быть.
5) Критичность низкая (1).

**Comment by welder1976** [comment]
исправлено
