### ISSUE TITLE
Хранилище материалов леди Сены (object=231063)

### ISSUE THREAD

**Issue by SimeonGavrilov** [welder1976/bugreport-legacy-Dreanor#7]
1)Хранилище материалов леди Сены
2)https://ru.wowhead.com/object=231063
3)Отсутствует лут.
4) Должен присутствовать лут. ~19 единиц ресурсов гарнизона (по данным wowhead)
5) Критичность низкая(1)

**Comment by welder1976** [comment]
исправлено
