### ISSUE TITLE
Отсутствие дропа первобытного духа(item=120945) из месторождений.

### ISSUE THREAD

**Issue by SimeonGavrilov** [welder1976/bugreport-legacy-Dreanor#8]
1) Отсутствие дропа первобытного духа из месторождений:
2) а)https://ru.wowhead.com/object=232544
    б)https://ru.wowhead.com/object=232542
    в)https://ru.wowhead.com/object=232545
    г)https://ru.wowhead.com/object=232543

3)Отсутствует дроп первобытного духа из вышеуказанных месторождений
4)Первобытный дух должен падать в соответствии с таблицами wowhead
5)Критичность средняя (2)

**Comment by welder1976** [comment]
исправлено
