### ISSUE TITLE
Отсутствие дропа дренорского камня(item=115508) в месторождениях.

### ISSUE THREAD

**Issue by SimeonGavrilov** [welder1976/bugreport-legacy-Dreanor#9]
1)Отсутствие дропа https://ru.wowhead.com/item=115508
2)а)https://ru.wowhead.com/object=232544
   б)https://ru.wowhead.com/object=232542
   в)https://ru.wowhead.com/object=232545
   г)https://ru.wowhead.com/object=232543
3) Отсутствует дроп дренорского камня(https://ru.wowhead.com/item=115508).
4) Камень должен падать в соответствии с шансами, указанными в таблице wowhead.
5) Критичность низкая (1)

**Comment by welder1976** [comment]
исправлено
